name: TaxiFleet Backend Dev CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: taxifleet-backend
        tags: dev_latest
        dockerfile: Dockerfile.dev
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: |
          res=`curl -sS -X POST \
          --header "Authorization: Goli-Auth-Key ${{ secrets.DEPLOY_AUTH_KEY }}" \
          https://goli.csmk59.de/api/v1/pipelines/5/run`
          
          [ $? -ne 0 ] && exit 3
          echo $res | jq -r '.description'
          code=`echo $res | jq -r '.statusCode'`
          echo "statusCode: $code"
          [ $code -ne 200 ] && exit 3 || exit 0